Metrics/MethodLength:
  Max: 80

Metrics/AbcSize:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/StringLiterals:
  Exclude:
    - test/**/*.rb
